### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by thorsten-stripe** [stripe/stripe-react-native#151]
## Pre release
- [x] Replace all instances of `stripe-react-native` with `@stripe/react-native`
- [x] Add versioning
- [x] Add CHANGELOG.md file
- [x] Update to the latest stripe-ios and stripe-android versions
- [x] Polish the README
- [x] Reorder example/src/screens/HomeScreen.tsx
- [x] Ungate Stripe docs
- [x] Add Stripe docs links to README

## Fast follows
- [ ] Set up github action for publishing the API ref on github pages
